// TODO: Remove dummy data once Supabase is seeded with real data
import { Client, FollowUp, Deal, Listing, QuizQuestion } from './types'

export const DUMMY_CLIENTS: Client[] = [
  {
    id: 'dummy-client-1',
    name: 'Maria Santos',
    phone: '(305) 812-4491',
    email: 'maria.santos@gmail.com',
    budget_min: 450000,
    budget_max: 650000,
    preferred_areas: 'Miami Beach, South Beach',
    status: 'prospect',
    source: 'Zillow',
    created_at: '2026-02-10T14:22:00Z',
  },
  {
    id: 'dummy-client-2',
    name: 'James Anderson',
    phone: '(786) 334-9021',
    email: 'j.anderson@outlook.com',
    budget_min: 800000,
    budget_max: 1200000,
    preferred_areas: 'Coral Gables, Coconut Grove',
    status: 'active',
    source: 'Referral',
    created_at: '2026-01-20T09:15:00Z',
  },
  {
    id: 'dummy-client-3',
    name: 'Linda Chen',
    phone: '(954) 677-2183',
    email: 'linda.chen@techcorp.com',
    budget_min: 550000,
    budget_max: 750000,
    preferred_areas: 'Brickell, Downtown Miami',
    status: 'active',
    source: 'Instagram',
    created_at: '2026-01-28T11:40:00Z',
  },
  {
    id: 'dummy-client-4',
    name: 'Robert Williams',
    phone: '(305) 991-5567',
    email: 'rwilliams@gmail.com',
    budget_min: 300000,
    budget_max: 420000,
    preferred_areas: 'Aventura, Hallandale',
    status: 'closed',
    source: 'Open House',
    created_at: '2025-11-05T16:30:00Z',
  },
  {
    id: 'dummy-client-5',
    name: 'Sofia Ramirez',
    phone: '(786) 541-0032',
    email: 'sofia.r@yahoo.com',
    budget_min: 380000,
    budget_max: 520000,
    preferred_areas: 'Kendall, Doral',
    status: 'prospect',
    source: 'Realtor.com',
    created_at: '2026-02-28T10:00:00Z',
  },
  {
    id: 'dummy-client-6',
    name: 'David Park',
    phone: '(305) 228-7741',
    email: 'dpark@finance.com',
    budget_min: 700000,
    budget_max: 950000,
    preferred_areas: 'Coconut Grove, Pinecrest',
    status: 'active',
    source: 'LinkedIn',
    created_at: '2026-02-01T13:55:00Z',
  },
  {
    id: 'dummy-client-7',
    name: 'Jennifer Thompson',
    phone: '(954) 302-8864',
    email: 'jthompson@medical.org',
    budget_min: 600000,
    budget_max: 850000,
    preferred_areas: 'Coral Gables, South Miami',
    status: 'prospect',
    source: 'Referral',
    created_at: '2026-03-05T08:30:00Z',
  },
  {
    id: 'dummy-client-8',
    name: 'Michael Brown',
    phone: '(786) 765-4421',
    email: 'mbrown@consulting.io',
    budget_min: 250000,
    budget_max: 350000,
    preferred_areas: 'Hialeah, Doral',
    status: 'closed',
    source: 'Zillow',
    created_at: '2025-10-12T15:20:00Z',
  },
]

export const DUMMY_FOLLOW_UPS: FollowUp[] = [
  { id: 'fu-1', client_id: 'dummy-client-1', note: 'Called Maria — interested in 2/2 near the beach. Sending listings this week.', created_at: '2026-03-12T10:30:00Z' },
  { id: 'fu-2', client_id: 'dummy-client-1', note: 'Showed 3 units on Collins Ave. She liked 8B but wants more options first.', created_at: '2026-03-01T14:00:00Z' },
  { id: 'fu-3', client_id: 'dummy-client-1', note: 'Initial inquiry via Zillow — looking for oceanfront under $650K.', created_at: '2026-02-10T14:22:00Z' },
  { id: 'fu-4', client_id: 'dummy-client-2', note: 'James confirmed pre-approval up to $1.15M. Ready to offer on Granada.', created_at: '2026-03-10T09:00:00Z' },
  { id: 'fu-5', client_id: 'dummy-client-2', note: 'Toured 3 homes in Coral Gables. 750 Granada Blvd is the front-runner.', created_at: '2026-02-22T11:30:00Z' },
  { id: 'fu-6', client_id: 'dummy-client-2', note: 'First call — referred by Tom Harris. Wants 4BD/3BA with pool, $800K–1.2M.', created_at: '2026-01-20T09:15:00Z' },
  { id: 'fu-7', client_id: 'dummy-client-3', note: 'Linda accepted counter-offer at $672K. Inspection scheduled for March 18.', created_at: '2026-03-13T16:00:00Z' },
  { id: 'fu-8', client_id: 'dummy-client-3', note: 'Offer submitted on 1200 Brickell Unit 22C at $665K. Seller countered $680K.', created_at: '2026-03-08T14:30:00Z' },
  { id: 'fu-9', client_id: 'dummy-client-3', note: 'Toured 4 Brickell condos. Unit 22C was the clear favorite.', created_at: '2026-02-14T10:00:00Z' },
  { id: 'fu-10', client_id: 'dummy-client-4', note: 'Closing completed. Robert is thrilled. Asked for referral cards.', created_at: '2026-01-15T11:00:00Z' },
  { id: 'fu-11', client_id: 'dummy-client-4', note: 'Final walkthrough done. Keys handed over on Jan 15.', created_at: '2026-01-14T15:00:00Z' },
  { id: 'fu-12', client_id: 'dummy-client-5', note: 'First showing scheduled for March 17 — 4 homes in Kendall area.', created_at: '2026-03-14T10:00:00Z' },
  { id: 'fu-13', client_id: 'dummy-client-5', note: 'Sofia reached out via Realtor.com. First-time buyer, pre-approved $480K.', created_at: '2026-02-28T10:00:00Z' },
  { id: 'fu-14', client_id: 'dummy-client-6', note: 'David toured 880 S Bayshore. Very interested — wants 2nd showing with architect.', created_at: '2026-03-11T13:00:00Z' },
  { id: 'fu-15', client_id: 'dummy-client-6', note: 'Discussed flexibility up to $1M for the right waterfront property.', created_at: '2026-02-15T15:30:00Z' },
  { id: 'fu-16', client_id: 'dummy-client-7', note: 'Jennifer sent wish list: 3+BD, home office, quiet street. Matching listings now.', created_at: '2026-03-07T09:45:00Z' },
  { id: 'fu-17', client_id: 'dummy-client-7', note: 'Referral from Dr. Patel. Relocating from NYC in summer — flexible timeline.', created_at: '2026-03-05T08:30:00Z' },
  { id: 'fu-18', client_id: 'dummy-client-8', note: 'Closed on 247 W 68th St, Hialeah at $310K. Commission received.', created_at: '2025-12-20T14:00:00Z' },
  { id: 'fu-19', client_id: 'dummy-client-8', note: 'Offer accepted at $310K. Scheduled closing for Dec 20.', created_at: '2025-12-05T10:00:00Z' },
]

export const DUMMY_DEALS: Deal[] = [
  {
    id: 'dummy-deal-1',
    client_id: 'dummy-client-1',
    property_address: '1420 Collins Ave, Unit 8B, Miami Beach, FL 33139',
    stage: 'prospect',
    appointment_at: null,
    offer_amount: null,
    sale_price: null,
    close_date: null,
    commission: null,
    notes: 'Interested in oceanfront 2/2. Pre-approval in progress.',
    updated_at: '2026-03-12T10:30:00Z',
    created_at: '2026-02-10T14:22:00Z',
    clients: { name: 'Maria Santos' },
  },
  {
    id: 'dummy-deal-5',
    client_id: 'dummy-client-5',
    property_address: '11340 SW 147th Ave, Kendall, FL 33196',
    stage: 'prospect',
    appointment_at: null,
    offer_amount: null,
    sale_price: null,
    close_date: null,
    commission: null,
    notes: 'First-time buyer. Needs guidance on the process.',
    updated_at: '2026-03-14T10:00:00Z',
    created_at: '2026-02-28T10:00:00Z',
    clients: { name: 'Sofia Ramirez' },
  },
  {
    id: 'dummy-deal-7',
    client_id: 'dummy-client-7',
    property_address: '715 Alhambra Cir, Coral Gables, FL 33134',
    stage: 'prospect',
    appointment_at: null,
    offer_amount: null,
    sale_price: null,
    close_date: null,
    commission: null,
    notes: 'Physician relocating from NYC. Flexible timeline, serious buyer.',
    updated_at: '2026-03-07T09:45:00Z',
    created_at: '2026-03-05T08:30:00Z',
    clients: { name: 'Jennifer Thompson' },
  },
  {
    id: 'dummy-deal-2',
    client_id: 'dummy-client-2',
    property_address: '750 Granada Blvd, Coral Gables, FL 33134',
    stage: 'appointment',
    appointment_at: '2026-03-17T10:00:00Z',
    offer_amount: null,
    sale_price: null,
    close_date: null,
    commission: null,
    notes: 'Second showing with spouse. Pre-approved up to $1.15M.',
    updated_at: '2026-03-10T09:00:00Z',
    created_at: '2026-01-20T09:15:00Z',
    clients: { name: 'James Anderson' },
  },
  {
    id: 'dummy-deal-6',
    client_id: 'dummy-client-6',
    property_address: '880 S Bayshore Dr, Coconut Grove, FL 33133',
    stage: 'appointment',
    appointment_at: '2026-03-19T14:00:00Z',
    offer_amount: null,
    sale_price: null,
    close_date: null,
    commission: null,
    notes: 'Second viewing with architect to assess renovation potential.',
    updated_at: '2026-03-11T13:00:00Z',
    created_at: '2026-02-01T13:55:00Z',
    clients: { name: 'David Park' },
  },
  {
    id: 'dummy-deal-3',
    client_id: 'dummy-client-3',
    property_address: '1200 Brickell Ave, Unit 22C, Miami, FL 33131',
    stage: 'pending',
    appointment_at: null,
    offer_amount: 672000,
    sale_price: null,
    close_date: null,
    commission: null,
    notes: 'Under contract at $672K. Inspection March 18. Target close April 5.',
    updated_at: '2026-03-13T16:00:00Z',
    created_at: '2026-01-28T11:40:00Z',
    clients: { name: 'Linda Chen' },
  },
  {
    id: 'dummy-deal-4',
    client_id: 'dummy-client-4',
    property_address: '3201 NE 183rd St, Unit 512, Aventura, FL 33160',
    stage: 'sold',
    appointment_at: null,
    offer_amount: 390000,
    sale_price: 388500,
    close_date: '2026-01-15',
    commission: 11655,
    notes: 'Smooth closing. Buyer very satisfied.',
    updated_at: '2026-01-15T11:00:00Z',
    created_at: '2025-11-05T16:30:00Z',
    clients: { name: 'Robert Williams' },
  },
  {
    id: 'dummy-deal-8',
    client_id: 'dummy-client-8',
    property_address: '247 W 68th St, Hialeah, FL 33012',
    stage: 'sold',
    appointment_at: null,
    offer_amount: 315000,
    sale_price: 310000,
    close_date: '2025-12-20',
    commission: 9300,
    notes: 'First sale of the quarter.',
    updated_at: '2025-12-20T14:00:00Z',
    created_at: '2025-10-12T15:20:00Z',
    clients: { name: 'Michael Brown' },
  },
]

export const DUMMY_LISTINGS: Listing[] = [
  {
    id: 'dummy-listing-1',
    address: '1420 Collins Ave, Unit 8B, Miami Beach, FL 33139',
    price: 595000,
    beds: 2,
    baths: 2,
    sqft: 1150,
    status: 'active',
    photo_url: 'https://picsum.photos/seed/collins-miami/600/400',
    agent_name: 'Sarah Johnson',
    created_at: '2026-02-15T10:00:00Z',
  },
  {
    id: 'dummy-listing-2',
    address: '750 Granada Blvd, Coral Gables, FL 33134',
    price: 1090000,
    beds: 4,
    baths: 3,
    sqft: 2800,
    status: 'active',
    photo_url: 'https://picsum.photos/seed/granada-gables/600/400',
    agent_name: 'Marcus Rivera',
    created_at: '2026-01-25T09:00:00Z',
  },
  {
    id: 'dummy-listing-3',
    address: '880 S Bayshore Dr, Coconut Grove, FL 33133',
    price: 875000,
    beds: 3,
    baths: 2.5,
    sqft: 2100,
    status: 'active',
    photo_url: 'https://picsum.photos/seed/bayshore-grove/600/400',
    agent_name: 'Sarah Johnson',
    created_at: '2026-02-01T14:00:00Z',
  },
  {
    id: 'dummy-listing-4',
    address: '1200 Brickell Ave, Unit 22C, Miami, FL 33131',
    price: 672000,
    beds: 2,
    baths: 2,
    sqft: 1320,
    status: 'under_contract',
    photo_url: 'https://picsum.photos/seed/brickell-miami/600/400',
    agent_name: 'Marcus Rivera',
    created_at: '2026-01-28T11:00:00Z',
  },
  {
    id: 'dummy-listing-5',
    address: '715 Alhambra Cir, Coral Gables, FL 33134',
    price: 780000,
    beds: 3,
    baths: 3,
    sqft: 2200,
    status: 'under_contract',
    photo_url: 'https://picsum.photos/seed/alhambra-circle/600/400',
    agent_name: 'Sarah Johnson',
    created_at: '2026-03-01T08:00:00Z',
  },
  {
    id: 'dummy-listing-6',
    address: '11340 SW 147th Ave, Unit 203, Kendall, FL 33196',
    price: 465000,
    beds: 3,
    baths: 2,
    sqft: 1680,
    status: 'under_contract',
    photo_url: 'https://picsum.photos/seed/kendall-sw/600/400',
    agent_name: 'Marcus Rivera',
    created_at: '2026-02-20T13:00:00Z',
  },
  {
    id: 'dummy-listing-7',
    address: '3201 NE 183rd St, Unit 512, Aventura, FL 33160',
    price: 388500,
    beds: 2,
    baths: 2,
    sqft: 1100,
    status: 'sold',
    photo_url: 'https://picsum.photos/seed/aventura-ne/600/400',
    agent_name: 'Sarah Johnson',
    created_at: '2025-11-10T10:00:00Z',
  },
  {
    id: 'dummy-listing-8',
    address: '247 W 68th St, Hialeah, FL 33012',
    price: 310000,
    beds: 3,
    baths: 1.5,
    sqft: 1340,
    status: 'sold',
    photo_url: 'https://picsum.photos/seed/hialeah-west/600/400',
    agent_name: 'Marcus Rivera',
    created_at: '2025-10-15T09:00:00Z',
  },
  {
    id: 'dummy-listing-9',
    address: '4250 Salzedo St, Coral Gables, FL 33146',
    price: 1250000,
    beds: 5,
    baths: 4,
    sqft: 3500,
    status: 'sold',
    photo_url: 'https://picsum.photos/seed/salzedo-gables/600/400',
    agent_name: 'Sarah Johnson',
    created_at: '2025-09-20T15:00:00Z',
  },
]

export const DUMMY_QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    id: 'dq-1',
    question: 'How many hours of pre-license education are required for a Florida real estate sales associate?',
    options: ['45 hours', '63 hours', '72 hours', '100 hours'],
    correct_index: 1,
    explanation: 'Florida requires 63 hours of pre-license education for sales associate candidates before sitting for the state exam.',
    category: 'licensing',
  },
  {
    id: 'dq-2',
    question: 'Under Florida law, how long must a broker maintain escrow account records?',
    options: ['1 year', '3 years', '5 years', '7 years'],
    correct_index: 2,
    explanation: 'Florida brokers are required to maintain escrow records for a minimum of 5 years.',
    category: 'escrow',
  },
  {
    id: 'dq-3',
    question: 'Which of the following is NOT a protected class under the federal Fair Housing Act?',
    options: ['Race', 'Religion', 'Sexual orientation', 'National origin'],
    correct_index: 2,
    explanation: 'Sexual orientation is not a protected class under the federal Fair Housing Act, though some states and localities have added it.',
    category: 'fair_housing',
  },
  {
    id: 'dq-4',
    question: 'In Florida, a real estate license expires every:',
    options: ['1 year', '2 years', '3 years', '4 years'],
    correct_index: 1,
    explanation: 'Florida real estate licenses are renewed on a 2-year cycle.',
    category: 'licensing',
  },
  {
    id: 'dq-5',
    question: 'A buyer\'s agent owes fiduciary duties to:',
    options: ['The seller', 'The buyer', 'Both buyer and seller equally', 'The MLS'],
    correct_index: 1,
    explanation: 'A buyer\'s agent represents the buyer and owes fiduciary duties solely to the buyer.',
    category: 'agency',
  },
  {
    id: 'dq-6',
    question: 'What is the maximum number of days allowed for a Florida broker to deposit escrow funds?',
    options: ['1 business day', '3 business days', '5 business days', '10 business days'],
    correct_index: 1,
    explanation: 'Brokers must deposit escrow funds within 3 business days of receipt.',
    category: 'escrow',
  },
  {
    id: 'dq-7',
    question: 'Which disclosure is required in Florida for all residential transactions of 4 units or fewer?',
    options: ['Mold disclosure', 'Seller\'s Property Disclosure', 'Lead-based paint disclosure (pre-1978 homes)', 'Radon disclosure'],
    correct_index: 2,
    explanation: 'Federal law requires lead-based paint disclosure for homes built before 1978 in transactions of 4 units or fewer.',
    category: 'disclosure',
  },
  {
    id: 'dq-8',
    question: 'Commingling in real estate refers to:',
    options: [
      'Mixing client funds with personal or business funds',
      'Listing a property with multiple brokers',
      'Representing both parties in a transaction',
      'Sharing commission with unlicensed persons',
    ],
    correct_index: 0,
    explanation: 'Commingling is the illegal mixing of client escrow funds with the broker\'s personal or business operating funds.',
    category: 'escrow',
  },
  {
    id: 'dq-9',
    question: 'Dual agency occurs when:',
    options: [
      'Two brokers represent the same buyer',
      'One agent represents both the buyer and seller in the same transaction',
      'A broker uses two MLS systems',
      'A buyer works with two agents simultaneously',
    ],
    correct_index: 1,
    explanation: 'Dual agency is when one agent or brokerage represents both the buyer and seller in the same transaction, requiring disclosure and consent.',
    category: 'agency',
  },
  {
    id: 'dq-10',
    question: 'In Florida, who regulates real estate licensees?',
    options: [
      'Florida Department of Business and Professional Regulation (DBPR)',
      'Florida Association of Realtors (FAR)',
      'Florida Real Estate Commission (FREC)',
      'National Association of Realtors (NAR)',
    ],
    correct_index: 2,
    explanation: 'The Florida Real Estate Commission (FREC) is the state body responsible for regulating real estate licensees under the DBPR.',
    category: 'licensing',
  },
  {
    id: 'dq-11',
    question: 'A listing agreement is a contract between:',
    options: ['Buyer and seller', 'Seller and listing broker', 'Buyer and buyer\'s agent', 'Lender and borrower'],
    correct_index: 1,
    explanation: 'A listing agreement is an employment contract between the property owner (seller) and the listing broker.',
    category: 'contracts',
  },
  {
    id: 'dq-12',
    question: 'Under Florida\'s Johnson v. Davis ruling, sellers must disclose:',
    options: [
      'Only structural defects',
      'Only defects visible during inspection',
      'Material facts that substantially affect property value and are not readily observable',
      'Only defects reported by a licensed inspector',
    ],
    correct_index: 2,
    explanation: 'Johnson v. Davis established that sellers must disclose known material facts that substantially affect the value of the property and are not readily observable by the buyer.',
    category: 'disclosure',
  },
  {
    id: 'dq-13',
    question: 'How many hours of post-license education must a Florida sales associate complete within the first renewal period?',
    options: ['14 hours', '30 hours', '45 hours', '60 hours'],
    correct_index: 2,
    explanation: 'Florida sales associates must complete 45 hours of post-license education during their first 2-year renewal period.',
    category: 'licensing',
  },
  {
    id: 'dq-14',
    question: 'An earnest money deposit is also known as:',
    options: ['Commission', 'Binder deposit / good-faith deposit', 'Down payment', 'Closing cost'],
    correct_index: 1,
    explanation: 'Earnest money, also called a binder or good-faith deposit, shows the buyer\'s serious intent to purchase.',
    category: 'contracts',
  },
  {
    id: 'dq-15',
    question: 'Which type of listing gives the seller the right to sell the property themselves without paying a commission?',
    options: ['Exclusive right-to-sell', 'Exclusive agency listing', 'Open listing', 'Net listing'],
    correct_index: 1,
    explanation: 'An exclusive agency listing allows the seller to sell the property on their own without owing a commission, while still giving the broker exclusive rights otherwise.',
    category: 'contracts',
  },
]
